<?php

namespace Database\Seeders;

use App\Models\BooktokTopBook;
use Illuminate\Database\Seeder;

class BooktokTopBookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            ['rank_position' => 1, 'title' => 'A Court of Mist and Fury', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 2, 'title' => 'Six of Crows', 'author' => 'Leigh Bardugo'],
            ['rank_position' => 3, 'title' => 'The Cruel Prince', 'author' => 'Holly Black'],
            ['rank_position' => 4, 'title' => 'A Court of Thorns and Roses', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 5, 'title' => 'Bright Burns the Flame', 'author' => 'Angelina J. Steffort'],
            ['rank_position' => 6, 'title' => 'The Lightning Thief', 'author' => 'Rick Riordan'],
            ['rank_position' => 7, 'title' => 'Fourth Wing', 'author' => 'Rebecca Yarros'],
            ['rank_position' => 8, 'title' => 'The Inheritance Games', 'author' => 'Jennifer Lynn Barnes'],
            ['rank_position' => 9, 'title' => 'The Song of Achilles', 'author' => 'Madeline Miller'],
            ['rank_position' => 10, 'title' => 'A Court of Wings and Ruin', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 11, 'title' => 'Shatter Me', 'author' => 'Tahereh Mafi'],
            ['rank_position' => 12, 'title' => 'Caraval', 'author' => 'Stephanie Garber'],
            ['rank_position' => 13, 'title' => 'A Good Girl\'s Guide to Murder', 'author' => 'Holly Jackson'],
            ['rank_position' => 14, 'title' => 'The Seven Husbands of Evelyn Hugo', 'author' => 'Taylor Jenkins Reid'],
            ['rank_position' => 15, 'title' => 'House of Earth and Blood', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 16, 'title' => 'From Blood and Ash', 'author' => 'Jennifer L. Armentrout'],
            ['rank_position' => 17, 'title' => 'The Wicked King', 'author' => 'Holly Black'],
            ['rank_position' => 18, 'title' => 'The Queen of Nothing', 'author' => 'Holly Black'],
            ['rank_position' => 19, 'title' => 'Shadow and Bone', 'author' => 'Leigh Bardugo'],
            ['rank_position' => 20, 'title' => 'It Ends with Us', 'author' => 'Colleen Hoover'],
            ['rank_position' => 21, 'title' => 'The Selection', 'author' => 'Kiera Cass'],
            ['rank_position' => 22, 'title' => 'Throne of Glass', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 23, 'title' => 'A Court of Wings and Ruin', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 24, 'title' => 'Shatter Me', 'author' => 'Tahereh Mafi'],
            ['rank_position' => 25, 'title' => 'Red Queen', 'author' => 'Victoria Aveyard'],
            ['rank_position' => 26, 'title' => 'A Court of Silver Flames', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 27, 'title' => 'Divergent', 'author' => 'Veronica Roth'],
            ['rank_position' => 28, 'title' => 'Powerless', 'author' => 'Lauren Roberts'],
            ['rank_position' => 29, 'title' => 'Circe', 'author' => 'Madeline Miller'],
            ['rank_position' => 30, 'title' => 'A Court of Frost and Starlight', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 31, 'title' => 'A Court of Frost and Starlight', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 32, 'title' => 'Punk 57', 'author' => 'Penelope Douglas'],
            ['rank_position' => 33, 'title' => 'Once Upon a Broken Heart', 'author' => 'Stephanie Garber'],
            ['rank_position' => 34, 'title' => 'The Book Thief', 'author' => 'Markus Zusak'],
            ['rank_position' => 35, 'title' => 'The Wrath and the Dawn', 'author' => 'Renée Ahdieh'],
            ['rank_position' => 36, 'title' => 'Heartless', 'author' => 'Marissa Meyer'],
            ['rank_position' => 37, 'title' => 'The Song of Achilles', 'author' => 'Madeline Miller'],
            ['rank_position' => 38, 'title' => 'Kingdom of Ash', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 39, 'title' => 'Better Than the Movies', 'author' => 'Lynn Painter'],
            ['rank_position' => 40, 'title' => 'A Kingdom of Flesh and Fire', 'author' => 'Jennifer L. Armentrout'],
            ['rank_position' => 41, 'title' => 'City of Bones', 'author' => 'Cassandra Clare'],
            ['rank_position' => 42, 'title' => 'The Prison Healer', 'author' => 'Lynette Noni'],
            ['rank_position' => 43, 'title' => 'A Touch of Darkness', 'author' => 'Scarlett St. Clair'],
            ['rank_position' => 44, 'title' => 'Verity', 'author' => 'Colleen Hoover'],
            ['rank_position' => 45, 'title' => 'Legendborn', 'author' => 'Tracy Deonn'],
            ['rank_position' => 46, 'title' => 'The City of Brass', 'author' => 'S.A. Chakraborty'],
            ['rank_position' => 47, 'title' => 'The Poppy War', 'author' => 'R.F. Kuang'],
            ['rank_position' => 48, 'title' => 'To Kill a Kingdom', 'author' => 'Alexandra Christo'],
            ['rank_position' => 49, 'title' => 'Divine Rivals', 'author' => 'Rebecca Ross'],
            ['rank_position' => 50, 'title' => 'Crown of Midnight', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 51, 'title' => 'Legend', 'author' => 'Marie Lu'],
            ['rank_position' => 52, 'title' => 'Serpent & Dove', 'author' => 'Shelby Mahurin'],
            ['rank_position' => 53, 'title' => 'Empire of Storms', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 54, 'title' => 'The Night Circus', 'author' => 'Erin Morgenstern'],
            ['rank_position' => 55, 'title' => 'The Invisible Life of Addie LaRue', 'author' => 'V.E. Schwab'],
            ['rank_position' => 56, 'title' => 'We Were Liars', 'author' => 'E. Lockhart'],
            ['rank_position' => 57, 'title' => 'Crooked Kingdom', 'author' => 'Leigh Bardugo'],
            ['rank_position' => 58, 'title' => 'Assistant to the Villain', 'author' => 'Hannah Nicole Maehrer'],
            ['rank_position' => 59, 'title' => 'The Invisible Life of Addie LaRue', 'author' => 'V.E. Schwab'],
            ['rank_position' => 60, 'title' => 'Heir of Fire', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 61, 'title' => 'We Hunt the Flame', 'author' => 'Hafsah Faizal'],
            ['rank_position' => 62, 'title' => 'Queen of Shadows', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 63, 'title' => 'Powerless', 'author' => 'Lauren Roberts'],
            ['rank_position' => 64, 'title' => 'Tower of Dawn', 'author' => 'Sarah J. Maas'],
            ['rank_position' => 65, 'title' => 'The Priory of the Orange Tree', 'author' => 'Samantha Shannon'],
            ['rank_position' => 66, 'title' => 'The Stolen Heir', 'author' => 'Holly Black'],
            ['rank_position' => 67, 'title' => 'Cinder', 'author' => 'Marissa Meyer'],
            ['rank_position' => 68, 'title' => 'Babel: An Arcane History', 'author' => 'R.F. Kuang'],
            ['rank_position' => 69, 'title' => 'From Blood and Ash', 'author' => 'Jennifer L. Armentrout'],
            ['rank_position' => 70, 'title' => 'Behind Closed Doors', 'author' => 'B.A. Paris'],
            ['rank_position' => 71, 'title' => 'Good Girl, Bad Blood', 'author' => 'Holly Jackson'],
            ['rank_position' => 72, 'title' => 'As Good As Dead', 'author' => 'Holly Jackson'],
            ['rank_position' => 73, 'title' => 'Five Survive', 'author' => 'Holly Jackson'],
            ['rank_position' => 74, 'title' => 'The Reappearance of Rachel Price', 'author' => 'Holly Jackson'],
            ['rank_position' => 75, 'title' => 'Crier\'s War', 'author' => 'Nina Varela'],
            ['rank_position' => 76, 'title' => 'Emily Wilde\'s Encyclopaedia of Faeries', 'author' => 'Heather Fawcett'],
            ['rank_position' => 77, 'title' => 'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch', 'author' => 'Terry Pratchett'],
            ['rank_position' => 78, 'title' => 'The Starless Sea', 'author' => 'Erin Morgenstern'],
            ['rank_position' => 79, 'title' => 'The Iron King', 'author' => 'Julie Kagawa'],
            ['rank_position' => 80, 'title' => 'House of Salt and Sorrows', 'author' => 'Erin A. Craig'],
            ['rank_position' => 81, 'title' => 'Belladonna', 'author' => 'Adalyn Grace'],
            ['rank_position' => 82, 'title' => 'The Bridge Kingdom', 'author' => 'Danielle L. Jensen'],
            ['rank_position' => 83, 'title' => 'The Silent Patient', 'author' => 'Alex Michaelides'],
            ['rank_position' => 84, 'title' => 'You\'ve Reached Sam', 'author' => 'Dustin Thao'],
            ['rank_position' => 85, 'title' => 'The Shadows Between Us', 'author' => 'Tricia Levenseller'],
            ['rank_position' => 86, 'title' => 'Furyborn', 'author' => 'Claire Legrand'],
            ['rank_position' => 87, 'title' => 'Red Rising', 'author' => 'Pierce Brown'],
            ['rank_position' => 88, 'title' => 'Bone Crier\'s Moon', 'author' => 'Kathryn Purdie'],
            ['rank_position' => 89, 'title' => 'Six Crimson Cranes', 'author' => 'Elizabeth Lim'],
            ['rank_position' => 90, 'title' => 'King of Scars', 'author' => 'Leigh Bardugo'],
            ['rank_position' => 91, 'title' => 'Dance of Thieves', 'author' => 'Mary E. Pearson'],
            ['rank_position' => 92, 'title' => 'Binding 13', 'author' => 'Chloe Walsh'],
            ['rank_position' => 93, 'title' => 'The Reckoning', 'author' => 'Marisa Noelle'],
            ['rank_position' => 94, 'title' => 'Smile', 'author' => 'Raina Telgemeier'],
            ['rank_position' => 95, 'title' => 'Sisters', 'author' => 'Raina Telgemeier'],
            ['rank_position' => 96, 'title' => 'Today Tonight Tomorrow', 'author' => 'Rachel Lynn Solomon'],
            ['rank_position' => 97, 'title' => 'The Silent Sister', 'author' => 'Diane Chamberlain'],
            ['rank_position' => 98, 'title' => 'Check & Mate', 'author' => 'Ali Hazelwood'],
            ['rank_position' => 99, 'title' => 'The Crown of Gilded Bones', 'author' => 'Jennifer L. Armentrout'],
            ['rank_position' => 100, 'title' => 'A Study in Drowning', 'author' => 'Ava Reid'],
        ];

        $publicationYearsByTitle = [
            'A Court of Mist and Fury' => 2016,
            'Six of Crows' => 2015,
            'The Cruel Prince' => 2018,
            'A Court of Thorns and Roses' => 2015,
            'Bright Burns the Flame' => 2021,
            'The Lightning Thief' => 2005,
            'Fourth Wing' => 2023,
            'The Inheritance Games' => 2020,
            'The Song of Achilles' => 2011,
            'A Court of Wings and Ruin' => 2017,
            'Shatter Me' => 2011,
            'Caraval' => 2017,
            'A Good Girl\'s Guide to Murder' => 2019,
            'The Seven Husbands of Evelyn Hugo' => 2017,
            'House of Earth and Blood' => 2020,
            'From Blood and Ash' => 2020,
            'The Wicked King' => 2019,
            'The Queen of Nothing' => 2019,
            'Shadow and Bone' => 2012,
            'It Ends with Us' => 2016,
            'The Selection' => 2012,
            'Throne of Glass' => 2012,
            'Red Queen' => 2015,
            'A Court of Silver Flames' => 2021,
            'Divergent' => 2011,
            'Powerless' => 2023,
            'Circe' => 2018,
            'A Court of Frost and Starlight' => 2018,
            'Punk 57' => 2016,
            'Once Upon a Broken Heart' => 2021,
            'The Book Thief' => 2005,
            'The Wrath and the Dawn' => 2015,
            'Heartless' => 2016,
            'Kingdom of Ash' => 2018,
            'Better Than the Movies' => 2021,
            'A Kingdom of Flesh and Fire' => 2020,
            'City of Bones' => 2007,
            'The Prison Healer' => 2021,
            'A Touch of Darkness' => 2019,
            'Verity' => 2018,
            'Legendborn' => 2020,
            'The City of Brass' => 2017,
            'The Poppy War' => 2018,
            'To Kill a Kingdom' => 2018,
            'Divine Rivals' => 2023,
            'Crown of Midnight' => 2013,
            'Legend' => 2011,
            'Serpent & Dove' => 2019,
            'Empire of Storms' => 2016,
            'The Night Circus' => 2011,
            'The Invisible Life of Addie LaRue' => 2020,
            'We Were Liars' => 2014,
            'Crooked Kingdom' => 2016,
            'Assistant to the Villain' => 2023,
            'Heir of Fire' => 2014,
            'We Hunt the Flame' => 2019,
            'Queen of Shadows' => 2015,
            'Tower of Dawn' => 2017,
            'The Priory of the Orange Tree' => 2019,
            'The Stolen Heir' => 2023,
            'Cinder' => 2012,
            'Babel: An Arcane History' => 2022,
            'Behind Closed Doors' => 2016,
            'Good Girl, Bad Blood' => 2020,
            'As Good As Dead' => 2021,
            'Five Survive' => 2022,
            'The Reappearance of Rachel Price' => 2024,
            'Crier\'s War' => 2019,
            'Emily Wilde\'s Encyclopaedia of Faeries' => 2023,
            'Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch' => 1990,
            'The Starless Sea' => 2019,
            'The Iron King' => 2010,
            'House of Salt and Sorrows' => 2019,
            'Belladonna' => 2022,
            'The Bridge Kingdom' => 2018,
            'The Silent Patient' => 2019,
            'You\'ve Reached Sam' => 2021,
            'The Shadows Between Us' => 2020,
            'Furyborn' => 2018,
            'Red Rising' => 2014,
            'Bone Crier\'s Moon' => 2020,
            'Six Crimson Cranes' => 2021,
            'King of Scars' => 2019,
            'Dance of Thieves' => 2018,
            'Binding 13' => 2018,
            'The Reckoning' => 2017,
            'Smile' => 2010,
            'Sisters' => 2014,
            'Today Tonight Tomorrow' => 2020,
            'The Silent Sister' => 2014,
            'Check & Mate' => 2023,
            'The Crown of Gilded Bones' => 2021,
            'A Study in Drowning' => 2023,
        ];

        foreach ($books as $book) {
            $book['published_year'] = $publicationYearsByTitle[$book['title']] ?? null;

            BooktokTopBook::query()->updateOrCreate(
                ['rank_position' => $book['rank_position']],
                $book
            );
        }
    }
}
